export enum Intent {
  GREETING = 'GREETING',
  PRODUCT_SEARCH = 'PRODUCT_SEARCH',
  RECOMMENDATION = 'RECOMMENDATION',
  EDUCATION = 'EDUCATION',
  PRODUCT_COMPARISON = 'PRODUCT_COMPARISON',
  OUT_OF_SCOPE = 'OUT_OF_SCOPE',
}